#!/bin/bash
[ -n "$FruitShareCodes" ] && {
  FRUITSHARECODES="$FruitShareCodes"
}
[ -n "$PetShareCodes" ] && {
  PETSHARECODES="$PetShareCodes"
}
[ -n "$SuperMarketShareCodes" ] && {
  SUPERMARKET_SHARECODES="$SuperMarketShareCodes"
}

FRUITSHARECODES=${FRUITSHARECODES:-ab20ce7ec4294af6af5f11ce657e6bcb@2764c0d2f0c44a32906c895b3cca8c66@@0fda5c9ebd194434aaecbbdf0d8741af}
PETSHARECODES=${PETSHARECODES:-MTAxODc2NTEzNDAwMDAwMDAxNTU4NjYxMw==@MTAxODcxOTI2NTAwMDAwMDAxMjY2MjY3NQ==@@MTAxODc2NTEzMTAwMDAwMDAwMzYxMDM0OQ==}
PLANT_BEAN_SHARECODES=${PLANT_BEAN_SHARECODES:-4npkonnsy7xi23qpldd3r2j7uacjaa2lz2pdlji@ik7t7zkjpb2rs6zc7ufixlk6xa@@ll3bia54pjfx47gq5c2rmder7u}
SUPERMARKET_SHARECODES=${SUPERMARKET_SHARECODES:-}
DREAM_FACTORY_SHARE_CODES=${DREAM_FACTORY_SHARE_CODES:-9PaGlgx8gtP3cKazbBGjRA==@9fOktlj2KmMSdYWc5UMcWg==@@wjh7atYNRrHocUKdJ3GS0g==}
DDFACTORY_SHARECODES=${DDFACTORY_SHARECODES:-T0225KkcRx4QplfTKUz1l6UPdQCjVWnYaS5kRrbA@T01597g7GU9KrQGJYUMCjVWnYaS5kRrbA@@T012_bkiAkRItguJCjVWnYaS5kRrbA}
JDZZ_SHARECODES=${JDZZ_SHARECODES:-S5KkcRx4QplfTKUz1l6UPdQ@S97g7GU9KrQGJYUM@@S_bkiAkRItguJ}
JXNC_SHARECODES=${JXNC_SHARECODES:-@@@}
JDJOY_SHARECODES=${JDJOY_SHARECODES:-l4GnTqXVnMBegfYeYysadqt9zd5YaBeE@XkIxjLJEOjXgVEI_-HIiHw==@@YRtcTvrnL58O5qSJz0JnZw==}
JDNIAN_SHARECODES=${JDNIAN_SHARECODES:-}
JDNY_SHARECODES=${JDNY_SHARECODES:-}

FruitShareCodes=$FRUITSHARECODES
jdJoyRewardNotify=$JD_JOY_REWARD_NOTIFY
jdSuperMarketRewardNotify=$MARKET_REWARD_NOTIFY
joyRunFlag=$JOY_RUN_FLAG
jdSuperMarketUpgrade=$SUPERMARKET_UPGRADE
jdBusinessCircleJump=$BUSINESS_CIRCLE_JUMP
jdSuperMarketLottery=$SUPERMARKET_LOTTERY
jdFruitBeanCard=$FRUIT_BEAN_CARD
